package com.stafeewa.photocalorie.app.utils

object EnglishToRussianMap {
    private val translitMap = mapOf(
        'а' to "a", 'б' to "b", 'в' to "v", 'г' to "g", 'д' to "d", 'е' to "e", 'ё' to "e",
        'ж' to "zh", 'з' to "z", 'и' to "i", 'й' to "y", 'к' to "k", 'л' to "l", 'м' to "m",
        'н' to "n", 'о' to "o", 'п' to "p", 'р' to "r", 'с' to "s", 'т' to "t", 'у' to "u",
        'ф' to "f", 'х' to "kh", 'ц' to "ts", 'ч' to "ch", 'ш' to "sh", 'щ' to "sch",
        'ъ' to "", 'ы' to "y", 'ь' to "", 'э' to "e", 'ю' to "yu", 'я' to "ya"
    )

    val map = mapOf(
        "apple_pie" to "Яблочный пирог",
        "baby_back_ribs" to "Ребрышки по-домашнему",
        "baklava" to "Пахлава",
        "beef_carpaccio" to "Карпаччо из говядины",
        "beef_tartare" to "Тартар из говядины",
        "beet_salad" to "Салат из свеклы",
        "beignets" to "Бенье",
        "bibimbap" to "Пибимпап",
        "borsh" to "Борщ",
        "bread_pudding" to "Хлебный пудинг",
        "breakfast_burrito" to "Буррито на завтрак",
        "bruschetta" to "Брускетта",
        "buckwheat_with_meat" to "Гречка с мясом",
        "caesar_salad" to "Салат Цезарь",
        "cannoli" to "Канноли",
        "caprese_salad" to "Капрезе",
        "carrot_cake" to "Морковный торт",
        "ceviche" to "Севиче",
        "cheese_plate" to "Сырная тарелка",
        "cheesecake" to "Чизкейк",
        "chicken_curry" to "Карри из курицы",
        "chicken_quesadilla" to "Кесадилья с курицей",
        "chicken_wings" to "Куриные крылышки",
        "chocolate_cake" to "Шоколадный торт",
        "chocolate_mousse" to "Шоколадный мусс",
        "churros" to "Чуррос",
        "clam_chowder" to "Суп из моллюсков",
        "club_sandwich" to "Клубный сэндвич",
        "crab_cakes" to "Крабовые котлеты",
        "creme_brulee" to "Крем-брюле",
        "croque_madame" to "Крок-мадам",
        "cup_cakes" to "Капкейки",
        "deviled_eggs" to "Фаршированные яйца",
        "donuts" to "Пончики",
        "dumplings" to "Пельмени",
        "edamame" to "Эдамаме",
        "eggs_benedict" to "Яйца Бенедикт",
        "escargots" to "Улитки",
        "falafel" to "Фалафель",
        "filet_mignon" to "Филе-миньон",
        "fish_and_chips" to "Рыба с картошкой фри",
        "foie_gras" to "Фуа-гра",
        "french_fries" to "Картофель фри",
        "french_onion_soup" to "Луковый суп по-французски",
        "french_toast" to "Французский тост",
        "fried_calamari" to "Жареные кальмары",
        "fried_eggs" to "Яичница",
        "fried_rice" to "Жареный рис",
        "frozen_yogurt" to "Замороженный йогурт",
        "garlic_bread" to "Чесночный хлеб",
        "gnocchi" to "Ньокки",
        "greek_salad" to "Греческий салат",
        "grilled_cheese_sandwich" to "Сэндвич с плавленым сыром",
        "grilled_salmon" to "Лосось на гриле",
        "guacamole" to "Гуакамоле",
        "gyoza" to "Гёдза",
        "hamburger" to "Гамбургер",
        "hot_and_sour_soup" to "Кисло-острый суп",
        "hot_dog" to "Хот-дог",
        "huevos_rancheros" to "Уэвос ранчерос",
        "hummus" to "Хумус",
        "ice_cream" to "Мороженое",
        "lasagna" to "Лазанья",
        "lobster_bisque" to "Биск из омара",
        "lobster_roll_sandwich" to "Сэндвич с омаром",
        "macaroni_and_cheese" to "Макароны с сыром",
        "macarons" to "Макаронс",
        "miso_soup" to "Мисо-суп",
        "mussels" to "Мидии",
        "nachos" to "Начос",
        "omelette" to "Омлет",
        "onion_rings" to "Луковые кольца",
        "oysters" to "Устрицы",
        "pad_thai" to "Пад-тай",
        "paella" to "Паэлья",
        "pancakes" to "Блины",
        "panna_cotta" to "Панна-котта",
        "peking_duck" to "Утка по-пекински",
        "pho" to "Фо",
        "pizza" to "Пицца",
        "pork_chop" to "Свиная отбивная",
        "poutine" to "Путин",
        "prime_rib" to "Ростбиф",
        "pulled_pork_sandwich" to "Сэндвич с тянутой свининой",
        "ramen" to "Лапша рамен",
        "ravioli" to "Равиоли",
        "red_velvet_cake" to "Красный бархат",
        "risotto" to "Ризотто",
        "samosa" to "Самоса",
        "sashimi" to "Сашими",
        "scallops" to "Гребешки",
        "seaweed_salad" to "Салат из морской капусты",
        "semolina" to "Манная каша",
        "shrimp_and_grits" to "Креветки с мамалыгой",
        "spaghetti_bolognese" to "Спагетти болоньезе",
        "spaghetti_carbonara" to "Спагетти карбонара",
        "spring_rolls" to "Спринг-роллы",
        "steak" to "Стейк",
        "strawberry_shortcake" to "Клубничный пирог",
        "sushi" to "Суши",
        "tacos" to "Тако",
        "takoyaki" to "Такояки",
        "tiramisu" to "Тирамису",
        "tuna_tartare" to "Тартар из тунца",
        "waffles" to "Вафли",
        "buckwheat_porridge_crumbly" to "Гречневая каша рассыпчатая",
        "porridge_yantarnaya_with_apples" to "Каша \"Янтарная\" (из пшена с яблоками)",
        "porridge_boyarskaya_with_raisins" to "Каша боярская (из пшена с изюмом)",
        "viscous_millet_porridge_with_pumpkin" to "Каша вязкая из пшена с тыквой",
        "guryev_porridge" to "Каша гурьевская",
        "pumpkin_porridge_with_semolina" to "Каша из тыквы с манкой",
        "brown_semolina_porridge" to "Каша манная коричневая",
        "millet_porridge_with_dried_plums" to "Каша пшенная с сушеными сливами",
        "rice_porridge_with_cocoa" to "Каша рисовая с какао",
        "semolina_porridge_with_cranberry_juice" to "Манная каша на клюквенном соке",
        "semolina_porridge_with_carrots" to "Манная каша с морковью",
        "flour_porridge" to "Мучная каша",
        "rice_porridge_with_prunes" to "Рисовая каша с черносливом",
        "hungarian_rice_with_apricots" to "Рисовая с абрикосами по-венгерски",
        "apple_semolina_porridge" to "Яблочно-манная каша",
        "natural_egg_porridge" to "Яичная каша (натуральная)",
        "egg_porridge_with_vegetables_or_mushrooms" to "Яичная каша с овощами или грибами",
        "barley_porridge_with_potatoes" to "Ячневая каша с картофелем",
        "borscht_with_fresh_cabbage_and_potatoes_1_110" to "Борщ из свежей капусты и картофеля по 1-110",
        "kuban_borscht_with_zucchini" to "Борщ кубанский с кабачками",
        "summer_borscht_with_beet_tops" to "Борщ летний (с ботвой свеклы)",
        "summer_borscht_1_122" to "Борщ летний по 1-122",
        "moscow_borscht" to "Борщ московский",
        "borscht_1_110" to "Борщ по 1-110",
        "vegetarian_borscht" to "Борщ по-вегетариански",
        "borscht_with_cabbage_and_potatoes" to "Борщ с капустой и картофелем",
        "borscht_with_potatoes_1_112" to "Борщ с картофелем по 1-112",
        "borscht_with_prunes_and_mushrooms" to "Борщ с черносливом и грибами",
        "siberian_borscht" to "Борщ сибирский",
        "ukrainian_borscht" to "Борщ украинский",
        "ukrainian_borscht_1_122" to "Борщ украинский по 1-122",
        "cold_borscht" to "Борщ холодный",
        "cold_borscht_2" to "Борщ холодный (2)",
        "beef_soup" to "Говяжий суп",
        "dutch_green_soup" to "Голландский зеленый суп",
        "dutch_green_soup_zero" to "Голландский зеленый суп (0)",
        "pea_soup" to "Гороховый суп",
        "mushroom_borscht" to "Грибной борщ",
        "mushroom_soup" to "Грибной суп",
        "indian_chicken_soup" to "Куриный суп по-индийски",
        "chicken_soup_with_pasta" to "Куриный суп с макаронами",
        "lithuanian_cold_borscht" to "Литовский холодный борщ",
        "lepsyteph_broth_with_fried_nuts" to "Лэпсытепх (бульон с жареными орешками)",
        "milk_soup_with_carrots" to "Молочный суп с морковью",
        "meat_okroshka_with_kefir_and_beef_1_194" to "Окрошка мясная на кефире с говядиной, по 1-194",
        "meat_okroshka_with_sour_cream_and_beef_1_192" to "Окрошка мясная со сметаной и говядиной, по 1-192",
        "vegetable_okroshka_1_192" to "Окрошка овощная по 1-192",
        "karelian_mushroom_pohlebka" to "Похлебка грибная (карельское)",
        "sardine_pohlebka_in_pot" to "Похлебка из сардин в горшочке",
        "suvorov_style_pohlebka" to "Похлебка по-суворовски",
        "siberian_fish_pohlebka" to "Похлебка рыбная по-сибирски",
        "old_moscow_pohlebka" to "Похлебка старомосковская",
        "rassolnik" to "Рассольник",
        "rassolnik_zero" to "Рассольник (0)",
        "homemade_rassolnik" to "Рассольник домашний",
        "homemade_rassolnik_1_136" to "Рассольник домашний по 1-136",
        "leningrad_rassolnik" to "Рассольник ленинградский",
        "kuban_rassolnik" to "Рассольник по-кубански",
        "rice_mushroom_soup" to "Рисовый грибной суп",
        "cold_svekolnik" to "Свекольник холодный",
        "cold_svekolnik_1_198" to "Свекольник холодный по 1-198",
        "sweet_bilberry_soup_with_dumplings" to "Сладкий суп из черники с клецками",
        "mushroom_solyanka_1_172" to "Солянка грибная по 1-172",
        "fish_solyanka_1_170" to "Солянка рыбная, по 1-170",
        "mixed_meat_solyanka_1_168" to "Солянка сборная мясная, по 1-168",
        "yerevan_soup" to "Суп \"Ереванский\"",
        "khinkal_soup_with_meat_and_shells" to "Суп \"Хинкал\" (с мясом и ракушками)",
        "cherry_soup_with_dumplings" to "Суп вишневый с клецками",
        "pea_soup_with_apples" to "Суп гороховый с яблоками",
        "mushroom_potato_soup" to "Суп грибной картофельный",
        "mushroom_soup_with_pies" to "Суп грибной с пирожками",
        "ceps_soup_with_pasta" to "Суп из белых грибов с макаронами",
        "beef_soup_2" to "Суп из говядины",
        "cranberry_and_apple_soup" to "Суп из клюквы и яблок",
        "carrot_and_kefir_soup" to "Суп из моркови и кефира",
        "vegetable_soup" to "Суп из овощей",
        "oatmeal_soup_with_apples" to "Суп из овсяной крупы с яблоками",
        "oat_flake_soup_with_apples" to "Суп из овсяных хлопьев с яблоками",
        "fresh_fruit_soup" to "Суп из плодов свежих",
        "fresh_tomato_soup" to "Суп из свежих помидоров",
        "fresh_fruit_soup_1_200" to "Суп из свежих фруктов по 1-200",
        "beet_tops_and_sorrel_soup" to "Суп из свекольной ботвы и щавеля",
        "dried_fruit_mix_soup" to "Суп из смеси сухофруктов",
        "asparagus_soup" to "Суп из спаржи",
        "duck_soup" to "Суп из утки",
        "bean_soup_with_nuts" to "Суп из фасоли с орехами",
        "cauliflower_soup" to "Суп из цветной капусты",
        "bilberry_soup_with_dumplings" to "Суп из черники с клецками",
        "bilberry_soup_with_pasta" to "Суп из черники с макаронами",
        "lentil_soup" to "Суп из чечевицы",
        "potato_soup" to "Суп картофельный",
        "potato_soup_1_142" to "Суп картофельный по 1-142",
        "potato_soup_with_beans" to "Суп картофельный с бобовыми",
        "potato_soup_with_mushrooms" to "Суп картофельный с грибами",
        "potato_soup_with_squid" to "Суп картофельный с кальмарами",
        "potato_soup_with_cereals" to "Суп картофельный с крупой",
        "potato_soup_with_pasta" to "Суп картофельный с макаронными изделиями",
        "potato_soup_with_meat_meatballs" to "Суп картофельный с мясными фрикадельками",
        "potato_soup_with_barley_1_146" to "Суп картофельный с перловой крупой по 1-146",
        "potato_soup_with_fish_meatballs" to "Суп картофельный с рыбными фрикадельками",
        "potato_soup_with_sweet_pepper" to "Суп картофельный со сладким перцем",
        "mushroom_noodle_soup" to "Суп лапша грибная",
        "rice_milk_soup" to "Суп молочный рисовый",
        "milk_soup_with_white_cabbage_1_180" to "Суп молочный с белокочанной капустой, по 1-180",
        "milk_soup_with_mushrooms" to "Суп молочный с грибами",
        "milk_soup_with_potato_shavings" to "Суп молочный с картофельными \"стружками\"",
        "milk_soup_with_dumplings" to "Суп молочный с клецками",
        "milk_soup_with_cereals" to "Суп молочный с крупой",
        "milk_soup_with_pasta_1_172" to "Суп молочный с макаронами, по 1-172",
        "milk_soup_with_pasta_products" to "Суп молочный с макаронными изделиями",
        "milk_soup_with_vegetables" to "Суп молочный с овощами",
        "milk_soup_with_rice" to "Суп молочный с рисом",
        "milk_soup_with_rice_2" to "Суп молочный с рисом (2)",
        "milk_soup_with_rice_1_174" to "Суп молочный с рисом, по 1-174",
        "milk_soup_with_pumpkin" to "Суп молочный с тыквой",
        "milk_soup_with_pumpkin_and_semolina_1_178" to "Суп молочный с тыквой и манной крупой, по 1-178",
        "vegetable_soup_on_rosehip_broth" to "Суп овощной на отваре шиповника",
        "barley_soup_with_mushrooms_1_164" to "Суп перловый с грибами по 1-164",
        "spicy_soup_with_shrimp" to "Суп пикантный с креветками",
        "field_soup" to "Суп полевой",
        "millet_soup_with_meat_1_160" to "Суп пшенный с мясом по 1-160",
        "rice_soup_1_158" to "Суп рисовый по 1-158",
        "bean_soup_1_162" to "Суп с бобовыми (фасоль) по 1-162",
        "soup_with_cereals" to "Суп с крупой",
        "soup_with_pasta" to "Суп с макаронными изделиями",
        "soup_with_barley" to "Суп с перловой крупой",
        "soup_with_fish_dumplings" to "Суп с рыбными вареничками",
        "soup_with_fish_meatballs" to "Суп с рыбными фрикадельками",
        "soup_with_meatballs" to "Суп с фрикадельками",
        "spinach_and_mushroom_soup" to "Суп со шпинатом и грибами",
        "bean_soup_2" to "Суп фасолевый",
        "kharcho_soup_with_meat_1_164" to "Суп харчо с мясом по 1-164",
        "cold_tarator_soup" to "Суп холодный \"Таратор\"",
        "pumpkin_cream_soup" to "Суп-крем из тыквы",
        "homemade_noodle_soup" to "Суп-лапша домашняя",
        "kazak_style_noodle_soup_with_tomatoes" to "Суп-лапша с помидорами по-казачьи",
        "green_pea_puree_soup" to "Суп-пюре из зеленого горошка",
        "zucchini_or_pumpkin_puree_soup" to "Суп-пюре из кабачков или тыквы",
        "potato_and_carrot_puree_soup" to "Суп-пюре из картофеля и моркови",
        "potato_puree_soup_1_180" to "Суп-пюре из картофеля по 1-180",
        "carrot_puree_soup_1_182" to "Суп-пюре из моркови по 1-182",
        "liver_puree_soup" to "Суп-пюре из печени",
        "poultry_puree_soup" to "Суп-пюре из птицы",
        "mixed_vegetable_puree_soup" to "Суп-пюре из разных овощей",
        "rice_puree_soup_1_186" to "Суп-пюре из рисовой крупы по 1-186",
        "fresh_tomato_puree_soup" to "Суп-пюре из свежих помидоров",
        "bilberry_puree_soup" to "Суп-пюре из черники",
        "spinach_puree_soup_1_184" to "Суп-пюре из шпината по 1-184",
        "garden_soup_salad" to "Суп-салат \"Садовый\"",
        "soup_kharcho" to "Суп-харчо",
        "georgian_kharcho" to "Суп-харчо (грузинское)",
        "cheese_soup" to "Сырный суп",
        "ladoga_ukha_with_quenelles_and_rasstegai" to "Уха ладожская с кнелями и расстегаями",
        "rostov_ukha" to "Уха ростовская",
        "fisherman_ukha" to "Уха рыбацкая",
        "ukha_with_barley" to "Уха с перловой крупой",
        "ukha_with_rasstegai" to "Уха с расстегаями",
        "bean_soup_3" to "Фасолевый суп",
        "kharcho_2" to "Харчо",
        "khirmasa_offal_soup_with_noodles" to "Хирмаса (суп из субпродуктов с лапшой)",
        "cold_borscht_with_radish" to "Холодный борщ с редькой",
        "boyar_cabbage_soup" to "Щи боярские",
        "green_cabbage_soup_with_egg" to "Щи зеленые с яйцом",
        "sauerkraut_cabbage_soup" to "Щи из квашеной капусты",
        "sauerkraut_cabbage_soup_2" to "Щи из квашеной капусты (2)",
        "sauerkraut_cabbage_soup_1_132" to "Щи из квашеной капусты по 1-132",
        "clover_and_sorrel_cabbage_soup" to "Щи из клевера и щавеля",
        "fresh_white_cabbage_soup" to "Щи из свежей белокочанной капусты",
        "fresh_cabbage_soup" to "Щи из свежей капусты",
        "fresh_cabbage_soup_1_130" to "Щи из свежей капусты по 1-130",
        "fresh_cabbage_soup_with_potatoes" to "Щи из свежей капусты с картофелем",
        "sorrel_cabbage_soup" to "Щи из щавеля",
        "sorrel_cabbage_soup_1_132" to "Щи из щавеля по 1-132",
        "urals_style_cabbage_soup_with_cereals" to "Щи по-уральски (с крупой)",
        "cabbage_soup_with_barley" to "Щи с ячневой крупой",
        "daily_cabbage_soup" to "Щи суточные",
        "daily_cabbage_soup_1_134" to "Щи суточные по 1-134",
        "braised_cabbage_soup_with_buckwheat_pancakes" to "Щи томленые с гречневыми блинами",
        "potato_yushka_with_zucchini_and_tomatoes" to "Юшка картофельная с кабачками и помидорами",
        "apple_soup_with_sour_cream" to "Яблочный суп со сметаной",
        "vinaigrette" to "Винегрет",
        "vegetable_vinaigrette" to "Винегрет из овощей",
        "vegetable_and_fruit_vinaigrette" to "Винегрет из овощей и фруктов",
        "vinaigrette_with_vegetables_apples_and_herbs" to "Винегрет из овощей, яблок и зелени",
        "pepper_and_potato_vinaigrette" to "Винегрет из перца с картофелем",
        "fruit_and_vegetable_vinaigrette" to "Винегрет из фруктов и овощей",
        "vegetable_vinaigrette_simple" to "Винегрет овощной",
        "vegetable_vinaigrette_2" to "Винегрет овощной (2)",
        "romanian_vinaigrette" to "Винегрет по-румынски",
        "vinaigrette_with_canned_meat" to "Винегрет с консервированным мясом",
        "vinaigrette_with_herring" to "Винегрет с селедкой",
        "vinaigrette_with_herring_2" to "Винегрет с сельдью",
        "dietary_beet_and_apple_salad" to "Диетический салат из свеклы и яблок",
        "fried_universal_salad" to "Жареный салат \"Универсал\"",
        "carrot_salad" to "Морковный салат",
        "carrots_with_tomatoes_and_apples" to "Морковь с помидорами и яблоками",
        "cucumber_salad" to "Огуречный салат",
        "okroshka" to "Окрошка",
        "okroshka_2" to "Окрошка (2)",
        "meat_okroshka" to "Окрошка мясная",
        "vegetable_okroshka" to "Окрошка овощная",
        "mixed_meat_okroshka" to "Окрошка сборная мясная",
        "original_salad" to "Оригинальный салат",
        "colorful_summer_salad" to "Пестрый летний салат",
        "colorful_salad" to "Пестрый салат",
        "liver_salad" to "Печеночный салат",
        "spicy_salad" to "Пикантный салат",
        "tomatoes_with_cucumbers_and_peppers" to "Помидоры с огурцами и перцем",
        "tomatoes_with_cucumbers_and_apples" to "Помидоры с огурцами и яблоками",
        "tomatoes_with_garlic_dressing" to "Помидоры с чесночной заправкой",
        "tomatoes_stuffed_with_apple_and_cucumber_salad" to "Помидоры, фаршированные салатом из яблок и огурцов",
        "tomatoes_stuffed_with_apple_and_cucumber_salad_2" to "Помидоры, фаршированные салатом из яблок и огурцов. (2)",
        "radish_with_sour_cream" to "Редиска со сметаной",
        "radish_in_sour_cream" to "Редька в сметане",
        "fish_salad" to "Рыбный салат",
        "fish_salad_2" to "Рыбный салат (2)",
        "ak_idel_salad_fish_with_rice_bashkir_style" to "Салат \"Ак-идель\" (рыбный с рисом по-башкирски)",
        "archpriest_salad" to "Салат \"Архиерейский\"",
        "spring_salad" to "Салат \"Весна\"",
        "capercaillie_nest_salad" to "Салат \"Гнездо глухаря\"",
        "pomegranate_salad" to "Салат \"Гранат\"",
        "pomegranate_bracelet_salad" to "Салат \"Гранатовый браслет\"",
        "mushroom_salad" to "Салат \"Грибки\"",
        "cinderella_salad" to "Салат \"Золушка\"",
        "kyiv_salad" to "Салат \"Киевский\"",
        "copenhagen_salad" to "Салат \"Копенгагенский\"",
        "kremlin_salad" to "Салат \"Кремлевский\"",
        "summer_salad" to "Салат \"Летний\"",
        "matryoshka_salad" to "Салат \"Матрешки\"",
        "mimosa_salad" to "Салат \"Мимоза\"",
        "moldova_salad" to "Салат \"Молдова\"",
        "moscow_salad" to "Салат \"Московский\"",
        "bride_salad" to "Салат \"Невеста\"",
        "tenderness_salad" to "Салат \"Нежность\"",
        "frying_salad" to "Салат \"Обжарка\"",
        "autumn_salad_with_fresh_vegetables_and_fish" to "Салат \"Осенний\" из свежих овощей с рыбой",
        "spicy_potato_salad_with_ham_and_garlic" to "Салат \"Острый\" из картофеля с ветчиной и чесноком",
        "petrovsky_mushroom_salad_with_sauerkraut_and_cucumbers" to "Салат \"Петровский\" грибной с квашеной капустой и огурцами",
        "pleasant_and_useful_salad" to "Салат \"Приятное с полезным\"",
        "quiet_backwater_salad" to "Салат \"Тихая заводь\"",
        "universal_salad" to "Салат \"Универсал\"",
        "fantasy_salad" to "Салат \"Фантазия\"",
        "caesar_salad_2" to "Салат \"Цезарь\"",
        "classic_caesar_salad" to "Салат \"Цезарь\" классический",
        "egoist_salad" to "Салат \"Эгоист\"",
        "exclusive_salad" to "Салат \"Эксклюзив\"",
        "experimental_salad" to "Салат \"Экспериментальный\"",
        "estonian_salad" to "Салат \"Эстонский\"",
        "vitamin_salad_1" to "Салат витаминный - 1",
        "vitamin_salad_2" to "Салат витаминный - 2",
        "pea_salad_with_apples" to "Салат гороховый с яблоками",
        "greek_salad" to "Салат греческий",
        "salad_for_men" to "Салат для мужчин",
        "orange_and_leek_salad" to "Салат из апельсинов и лука-порея",
        "white_cabbage_salad" to "Салат из белокачанной капусты",
        "white_cabbage_and_seaweed_salad" to "Салат из белокочанной и морской капусты",
        "white_cabbage_salad_with_squid" to "Салат из белокочанной капусты с кальмарами",
        "white_cabbage_salad_with_herring_and_bacon" to "Салат из белокочанной капусты с сельдью и шпиком",
        "white_cabbage_salad_with_apples_and_celery" to "Салат из белокочанной капусты с яблоками и сельдереем",
        "cep_or_champignon_salad" to "Салат из белых грибов или шампиньонов",
        "beans_salad" to "Салат из бобов",
        "mushroom_and_sauerkraut_salad" to "Салат из грибов и квашеной капусты",
        "mushroom_salad_with_herring" to "Салат из грибов с сельдью",
        "herb_salad_with_game" to "Салат из зелени с дичью",
        "zucchini_and_tomato_salad" to "Салат из кабачков и помидоров",
        "squid_salad_with_apples" to "Салат из кальмаров с яблоками",
        "cabbage_salad_with_oranges" to "Салат из капусты с апельсинами",
        "cabbage_salad_with_mushrooms" to "Салат из капусты с грибами",
        "cabbage_salad_with_apples" to "Салат из капусты с яблоками",
        "cabbage_salad_with_apples_2" to "Салат из капусты с яблоками (2)",
        "cabbage_salad_with_apples_and_onions" to "Салат из капусты с яблоками и луком",
        "potato_salad_with_seaweed_and_beets" to "Салат из картофеля с морской капустой и свеклой",
        "potato_salad_with_radish_and_apples" to "Салат из картофеля с редькой и яблоками",
        "sauerkraut_salad" to "Салат из квашенной капусты",
        "sauerkraut_and_beet_salad" to "Салат из квашенной капусты и свеклы",
        "sauerkraut_salad_2" to "Салат из квашеной капусты",
        "sauerkraut_salad_with_herring" to "Салат из квашеной капусты с селью",
        "kilka_in_tomato_sauce_salad" to "Салат из кильки в томатном соусе",
        "kohlrabi_salad" to "Салат из кольраби",
        "crab_salad" to "Салат из крабов",
        "red_sweet_pepper_green_peas_and_rice_salad" to "Салат из красного сладкого перца, зеленого горошка и риса",
        "red_cabbage_salad" to "Салат из краснокачанной капусты",
        "red_cabbage_salad_with_apples" to "Салат из краснокачанной капусты с яблоками",
        "red_cabbage_salad_2" to "Салат из краснокочанной капусты",
        "red_cabbage_salad_with_mushrooms" to "Салат из краснокочанной капусты с грибами",
        "shrimp_salad_with_rice" to "Салат из креветок с рисом",
        "corn_salad" to "Салат из кукурузы",
        "archangel_style_chicken_salad" to "Салат из курицы по-архангельски",
        "marinated_beet_salad_with_apples" to "Салат из маринованной свеклы с яблоками",
        "carrot_salad_2" to "Салат из моркови",
        "carrot_and_cabbage_salad" to "Салат из моркови и капусты",
        "carrot_salad_with_dried_apricots_tomatoes_and_apples" to "Салат из моркови с курагой, помидорами и яблоками",
        "carrot_salad_with_nuts_and_honey" to "Салат из моркови с орехами и медом",
        "carrot_salad_with_horseradish" to "Салат из моркови с хреном",
        "sea_scallop_salad_with_cucumbers" to "Салат из морского гребешка с огурцами",
        "vegetable_salad_with_seaweed" to "Салат из овощей с капустой морской",
        "cucumber_salad_2" to "Салат из огурцов",
        "cucumber_salad_zero" to "Салат из огурцов (0)",
        "pepper_salad" to "Салат из перца",
        "tomato_salad" to "Салат из помидоров",
        "tomato_and_cucumber_salad" to "Салат из помидоров и огурцов",
        "chilean_style_tomato_salad" to "Салат из помидоров по-чилийски",
        "tomato_cucumber_and_sweet_pepper_salad" to "Салат из помидоров, огурцов и сладкого перца",
        "poultry_or_game_salad" to "Салат из птицы или дичи",
        "poultry_or_game_salad_2" to "Салат из птицы или дичи (2)",
        "assorted_fruit_salad" to "Салат из разных фруктов",
        "radish_salad" to "Салат из редиса",
        "radish_salad_with_sour_cream" to "Салат из редиски со метаной",
        "radish_salad_2" to "Салат из редьки",
        "kabardian_style_radish_and_potato_salad" to "Салат из редьки и картофеля по-кабардински",
        "radish_salad_with_nuts" to "Салат из редьки с орехами",
        "turnip_salad" to "Салат из репы",
        "fish_salad_3" to "Салат из рыбы",
        "fresh_cabbage_salad_with_meat" to "Салат из свежей капусты с мясом",
        "fresh_vegetable_salad" to "Салат из свежих овощей",
        "beet_and_horseradish_salad" to "Салат из свеклы и хрена",
        "beet_salad_with_nuts" to "Салат из свеклы с орехами",
        "beet_salad_with_cheese_and_garlic" to "Салат из свеклы с сыром и чесноком",
        "beet_salad_with_horseradish" to "Салат из свеклы с хреном",
        "beet_salad_with_prunes_nuts_and_garlic" to "Салат из свеклы с черносливом, орехами и чесноком",
        "herring_salad" to "Салат из сельди",
        "pickled_cucumber_and_rutabaga_salad" to "Салат из соленых огурцов и брюквы",
        "pickled_cucumber_and_radish_salad" to "Салат из соленых огурцов и редьки",
        "pickled_cucumber_and_beet_salad" to "Салат из соленых огурцов и свеклы",
        "asparagus_salad" to "Салат из спаржи",
        "green_bean_salad" to "Салат из стручковой фасоли",
        "green_bean_salad_2" to "Салат из стручковой фасоли (2)",
        "raw_carrot_and_turnip_salad" to "Салат из сырой моркови и репы",
        "raw_carrot_and_apple_salad" to "Салат из сырой моркови м яблоками",
        "raw_beet_salad" to "Салат из сырой свеклы",
        "raw_vegetable_salad" to "Салат из сырых овощей",
        "raw_vegetable_salad_with_apples" to "Салат из сырых овощей с яблоками",
        "cottage_cheese_salad" to "Салат из творога",
        "cod_salad_with_mayonnaise" to "Салат из трески с майонезом",
        "cod_salad_with_horseradish" to "Салат из трески с хреном",
        "pumpkin_salad" to "Салат из тыквы",
        "chuvash_style_pumpkin_salad" to "Салат из тыквы по-чувашски",
        "pumpkin_and_apple_salad" to "Салат из тыквы с яблоками",
        "bean_salad" to "Салат из фасоли",
        "bean_salad_2" to "Салат из фасоли (2)",
        "fruit_salad" to "Салат из фруктов",
        "cauliflower_salad" to "Салат из цветной капусты",
        "cauliflower_salad_2" to "Салат из цветной капусты (2)",
        "cauliflower_fresh_cucumber_and_tomato_salad" to "Салат из цветной капусты, свежих огурцов и помидоров",
        "champignon_salad" to "Салат из шампиньонов",
        "sorrel_salad" to "Салат из щавеля",
        "apple_and_lingonberry_salad" to "Салат из яблок и брусники",
        "apple_and_onion_salad" to "Салат из яблок и лука",
        "apple_carrot_and_nut_salad" to "Салат из яблок и моркови с орехами",
        "apple_and_tomato_salad" to "Салат из яблок и помидоров",
        "apple_and_plum_salad" to "Салат из яблок и сливы",
        "apple_and_pumpkin_salad" to "Салат из яблок и тыквы",
        "apple_salad_with_nuts" to "Салат из яблок с орехами",
        "potato_salad_3" to "Салат картофельный",
        "potato_salad_with_mushrooms_and_lingonberries" to "Салат картофельный с грибами и брусникой",
        "potato_salad_with_mushrooms_and_cranberries" to "Салат картофельный с грибами и клюквой",
        "potato_salad_with_apples" to "Салат картофельный с яблоками",
        "amateur_salad" to "Салат любительский",
        "anthill_salad" to "Салат Муравейник",
        "meat_salad" to "Салат мясной",
        "meat_salad_2" to "Салат мясной (2)",
        "vegetable_salad_with_radish_and_apples" to "Салат овощной с редькой и яблоками",
        "vegetable_salad_with_apples_and_sweet_pepper" to "Салат овощной с яблоками и сладким перцем",
        "refreshing_salad_with_radish" to "Салат освежающий с редькой",
        "autumn_salad" to "Салат осенний",
        "berlin_style_salad" to "Салат по-берлински",
        "country_style_salad" to "Салат по-деревенски",
        "komi_permian_style_salad_sauerkraut_with_meat" to "Салат по-коми-пермяцки (из квашеной капусты с мясом)",
        "french_style_salad" to "Салат по-французски",
        "czech_style_salad" to "Салат по-чешски",
        "fish_salad_4" to "Салат рыбный",
        "fish_salad_5" to "Салат рыбный (2)",
        "fish_salad_with_seaweed" to "Салат рыбный с морской капустой",
        "squid_salad" to "Салат с кальмарами",
        "sausage_salad" to "Салат с колбасой",
        "smoked_cod_salad" to "Салат с копченой треской",
        "shrimp_salad" to "Салат с креветками",
        "corn_salad_2" to "Салат с кукурузой",
        "salad_with_oil_and_vinegar" to "Салат с маслом и уксусом",
        "sardine_salad" to "Салат с сардинами",
        "celery_and_cottage_cheese_salad" to "Салат с сельдереем и творогом",
        "seasonal_salad" to "Салат сезонный",
        "sour_cream_and_egg_salad" to "Салат со сметаной и яйцом",
        "capital_salad" to "Салат столичный",
        "fruit_salad_with_sour_cream_sauce" to "Салат фруктовый со сметанным соусом",
        "egg_salad" to "Салат яичный",
        "exotic_cocktail_salad" to "Салат-коктейль \"Экзотик\"",
        "vegetable_cocktail_salad" to "Салат-коктейль овощной",
        "fish_cocktail_salad" to "Салат-коктейль рыбный",
        "ham_and_cheese_cocktail_salad" to "Салат-коктейль с ветчиной и сыром",
        "chicken_and_fruit_cocktail_salad" to "Салат-коктейль с курицей и фруктами",
        "beet_in_sweet_marinade" to "Свекла в сладком маринаде",
        "beet_with_cranberries" to "Свекла с клюквой",
        "herring_under_fur_coat" to "Селедка \"под шубой\"",
        "grated_herring_with_butter" to "Сельдь протертая с маслом",
        "potato_cheese" to "Сыр картофельный",
        "layered_cheese" to "Сыр слоеный",
        "cheese_salad_2" to "Сырный салат",
        "cheese_salad_zero" to "Сырный салат (0)",
        "fake_olivier_salad" to "Фальшивый Оливье",
        "wild_garlic_with_butter" to "Черемша с маслом",
        "apple_salad_with_celery_and_tomatoes" to "Яблочный салат с сельдереем и помидорами",
        "egg_salad_2" to "Яичный салат",
        "azu" to "Азу",
        "entrecote" to "Антрекот",
        "anchovies_and_kilka_with_potatoes" to "Анчоусы и кильки с картофелем",
        "breaded_eggplants" to "Баклажаны панированные",
        "ukrainian_style_eggplants" to "Баклажаны по-украински",
        "eggplants_with_mayonnaise" to "Баклажаны под майонезом",
        "stewed_eggplants_with_tomatoes" to "Баклажаны тушеные с помидорами",
        "belyash" to "Беляш",
        "beef_stroganoff" to "Бефстроганов",
        "semolina_or_rice_patties" to "Биточки или котлеты манные, рисовые",
        "steamed_patties" to "Биточки паровые",
        "beefsteak" to "Бифштекс",
        "minced_beefsteak" to "Бифштекс рубленый",
        "bozbash" to "Бозбаш",
        "baked_rutabaga" to "Брюква запеченная",
        "lazy_varenyky_boiled" to "Вареники ленивые отварные",
        "varenyky_with_cabbage" to "Вареники с капустой",
        "varenyky_with_cottage_cheese_fruit_or_vegetable_filling" to "Вареники с творожным, фруктовым или овощным фаршем",
        "vol_au_vents_with_chicken" to "Волованы с курицей",
        "fish_galantine" to "Галантин из рыбы",
        "beef_in_sweet_and_sour_sauce" to "Говядина в кисло-сладком соусе",
        "vegetable_stuffed_cabbage_rolls" to "Голубцы овощные",
        "mushroom_casserole" to "Грибная запеканка",
        "mushroom_caviar" to "Грибная икра",
        "mushroom_pelmeni" to "Грибные пельмени",
        "mushrooms_in_sour_cream_sauce" to "Грибы в сметанном соусе",
        "fried_mushrooms" to "Грибы жареные",
        "goulash" to "Гуляш",
        "draniki" to "Драники",
        "siberian_hedgehogs" to "Ежики сибирские",
        "homestyle_roast" to "Жаркое по-домашнему",
        "zucchini_casserole" to "Запеканка из кабачков",
        "pasta_and_cottage_cheese_casserole" to "Запеканка из макарон с творогом",
        "cottage_cheese_casserole" to "Запеканка из творога",
        "pumpkin_casserole" to "Запеканка из тыквы",
        "potato_casserole_with_meat" to "Запеканка картофельная с мясом",
        "carrot_casserole" to "Запеканка морковная",
        "imam_bayildi" to "Имам баилди",
        "zucchini_stuffed_with_meat" to "Кабачки фаршированные мясом",
        "zucchini_stuffed_with_rice" to "Кабачки, фаршированные рисом",
        "fried_squid" to "Кальмары жареные",
        "stewed_cabbage" to "Капуста тушеная",
        "cabbage_cutlets" to "Капустные котлеты",
        "potato_cutlets" to "Картофельные котлеты",
        "potato_pancakes_with_cheese" to "Картофельные оладьи с сыром",
        "kyiv_cutlet" to "Котлета по-киевски",
        "pea_cutlets" to "Котлеты гороховые",
        "zucchini_cutlets_with_cottage_cheese" to "Котлеты из кабачков с творогом",
        "vegetable_cutlets" to "Котлеты из овощей",
        "potato_cutlets_2" to "Котлеты картофельные",
        "carrot_cutlets" to "Котлеты морковные",
        "minced_chicken_cutlets" to "Котлеты рубленые из кур",
        "fish_cutlets_amateur" to "Котлеты рыбные любительские",
        "beetroot_cutlets" to "Котлеты свекольные",
        "potato_croquettes" to "Крокеты картофельные",
        "rabbit_amateur_style" to "Кролик по-любительски",
        "merchant_style_chicken" to "Курица по-купечески",
        "langet" to "Лангет",
        "lyulya_kebab" to "Люля-кебаб",
        "manti_with_lamb" to "Манты с бараниной",
        "manti_with_pumpkin" to "Манты с тыквой",
        "glazed_carrots" to "Морковь глазированная",
        "stewed_carrots" to "Морковь тушеная",
        "boiled_meat" to "Мясо отварное",
        "french_style_meat" to "Мясо по-французски",
        "stewed_meat" to "Мясо тушеное",
        "vegetable_ragout" to "Овощное рагу",
        "natural_omelette" to "Омлет натуральный",
        "omelette_with_cheese" to "Омлет с сыром",
        "liver_pate" to "Паштет из печени",
        "moscow_pelmeni" to "Пельмени \"Московские\"",
        "beef_and_pork_pelmeni" to "Пельмени из говядины и свинины",
        "peppers_stuffed_with_vegetables_and_rice" to "Перец, фаршированный овощами и рисом",
        "stroganoff_style_liver" to "Печень по-строгановски",
        "chicken_plov" to "Плов с курицей",
        "beef_plov" to "Плов с говядиной",
        "podzharka" to "Поджарка",
        "tomatoes_stuffed_with_mushrooms" to "Помидоры, фаршированные грибами",
        "boiled_suckling_pig" to "Поросенок отварной",
        "vegetable_ragout_2" to "Рагу из овощей",
        "braised_rice" to "Рис припущенный",
        "romsteak" to "Ромштекс",
        "meat_roll_with_prunes" to "Рулет мясной с черносливом",
        "fried_fish" to "Рыба жареная",
        "russian_style_fish" to "Рыба по-русски",
        "fish_cutlets" to "Рыбные котлеты",
        "caesar_salad_with_chicken" to "Салат Цезарь с курицей",
        "olivier_salad" to "Салат Оливье",
        "greek_salad_2" to "Салат Греческий",
        "tuna_salad" to "Салат с тунцом",
        "stewed_beets" to "Свекла тушеная",
        "chinese_style_pork" to "Свинина по-китайски",
        "herring_with_potatoes" to "Сельдь с картофелем",
        "mixed_meat_solyanka" to "Солянка сборная мясная",
        "zander_baked_with_potatoes" to "Судак, запеченный с картофелем",
        "tefteli" to "Тефтели",
        "cod_with_mustard_sauce" to "Треска с горчичным соусом",
        "ukha_2" to "Уха",
        "stuffed_cucumbers" to "Фаршированные огурцы",
        "beans_with_prunes" to "Фасоль с черносливом",
        "turkey_fillet_stuffed_with_apples" to "Филе индейки, фаршированное яблоками",
        "forshmak" to "Форшмак",
        "meat_meatballs" to "Фрикадельки мясные",
        "boiled_cauliflower" to "Цветная капуста отварная",
        "tabaka_chicken" to "Цыплята табака",
        "chicken_chakhokhbili" to "Чахохбили из курицы",
        "chebureki" to "Чебуреки",
        "lamb_shashlik" to "Шашлык из баранины",
        "cabbage_schnitzel" to "Шницель из капусты",
        "escalope" to "Эскалоп",
        "tongue_boiled_in_sauce" to "Язык отварной в соусе",
        "fried_egg_with_vegetables" to "Яичница глазунья с овощами",
        "eggs_stuffed_with_shrimp" to "Яйца фаршированные креветками",
        "apple" to "Яблоко",
        "banana" to "Банан",
        "pear" to "Груша",
        "orange" to "Апельсин",
        "mandarin" to "Мандарин",
        "kiwi" to "Киви",
        "grape" to "Виноград",
        "watermelon" to "Арбуз",
        "melon" to "Дыня",
        "dried_fruits_mix" to "Сухофрукты микс",
        "nuts_mix" to "Орехи микс",
        "almond" to "Миндаль",
        "walnut" to "Грецкий орех",
        "cashew" to "Кешью",
        "protein_bar" to "Протеиновый батончик",
        "granola_bar" to "Злаковый батончик",
        "greek_yogurt" to "Йогурт греческий",
        "kefir" to "Кефир",
        "cottage_cheese_5_percent" to "Творог 5%",
        "orange_juice" to "Сок апельсиновый",
        "apricot_carbonated_cocktail" to "Абрикосовый газированный коктейль",
        "apricot_egg_nog" to "Абрикосовый гоголь-моголь",
        "apricot_dessert_drink" to "Абрикосовый десертный напиток",
        "apricot_cocktail_with_float" to "Абрикосовый коктейль с поплавком",
        "orange_milk" to "Апельсиновое молоко",
        "orange_compote" to "Апельсиновый компот",
        "buryat_tea" to "Бурятский чай",
        "hot_apricot_drink" to "Горячий абрикосовый напиток",
        "cocoa_with_milk" to "Какао с молоком",
        "cocoa_with_condensed_milk" to "Какао с молоком сгущенным",
        "rhubarb_kvass" to "Квас из ревеня",
        "cranberry_kvass" to "Квас клюквенный",
        "tobolsk_kvass" to "Квас по-тобольски",
        "bread_kvass_from_extract" to "Квас хлебный из экстракта",
        "apple_kvass" to "Квас яблочный",
        "kefir_with_rhubarb" to "Кефир с ревенем",
        "kefir_acidophilus_ryazhenka_prostokvasha" to "Кефир, ацидофилин, простокваша, ряженка",
        "orange_kissel" to "Кисель апельсиновый",
        "lingonberry_kissel" to "Кисель брусничный",
        "apricot_kissel" to "Кисель из абрикосов",
        "wild_strawberry_kissel" to "Кисель из земляники",
        "thick_cranberry_kissel" to "Кисель из клюквы (густой)",
        "concentrate_kissel_from_fruit_or_berry_extracts" to "Кисель из концентрата на плодовых или ягодных экстрактах",
        "oat_flake_kissel" to "Кисель из овсяных хлопьев",
        "fresh_fruit_and_berry_kissel" to "Кисель из плодов и ягод свежих",
        "thick_apple_kissel" to "Кисель из яблок (густой)",
        "milk_kissel" to "Кисель молочный",
        "thick_milk_kissel" to "Кисель молочный (густой)",
        "carrot_kissel" to "Кисель морковный",
        "jupiter_cocktail" to "Коктейль \"Юпитер\"",
        "milkshake" to "Коктейль молочный",
        "shrimp_cocktail" to "Коктейль с креветками",
        "apricot_compote" to "Компот из абрикосов",
        "quince_compote" to "Компот из айвы",
        "barberry_compote" to "Компот из барбариса",
        "cherry_compote" to "Компот из вишни",
        "carrot_compote" to "Компот из моркови",
        "canned_fruit_compote_2" to "Компот из плодов консервированных 2",
        "fresh_fruit_compote" to "Компот из свежих плодов",
        "beet_compote" to "Компот из свеклы",
        "dried_fruit_mix_compote" to "Компот из смеси сухофруктов",
        "pumpkin_and_rhubarb_compote" to "Компот из тыквы и ревеня",
        "bilberry_compote" to "Компот из черники",
        "apple_and_plum_or_apple_and_alycha_compote" to "Компот из яблок и слив или из яблок и алычи",
        "drupe_kissel" to "Костяничный кисель",
        "coffee_with_milk" to "Кофе на молоке",
        "warsaw_style_coffee_with_milk" to "Кофе на молоке по-варшавски",
        "coffee_with_condensed_milk" to "Кофе на молоке сгущенном",
        "eastern_style_coffee" to "Кофе по-восточному",
        "black_coffee_variant_1_for_espresso_machine" to "Кофе черный 1-ый вариант (для кофеварки типа \"Экспресс\")",
        "black_coffee_variant_2" to "Кофе черный 2-ой вариант",
        "black_coffee_with_ice_cream_glace" to "Кофе черный с мороженым (глясе)",
        "cold_coffee_drink" to "Кофейный холодный напиток",
        "creole_drink" to "Креольский напиток",
        "gooseberry_with_kefir" to "Крыжовник с кефиром",
        "lemon_kissel" to "Лимонный кисель",
        "zauralskaya_medovukha" to "Медовуха \"Зауральская\"",
        "boiled_milk" to "Молоко кипяченое",
        "milk_apricot_cocktail" to "Молочно-абрикосовый коктейль",
        "carrot_milk_kissel" to "Молочный кисель из моркови",
        "milk_drink_with_apricots" to "Молочный напиток с абрикосами",
        "lingonberry_mors" to "Морс брусничный",
        "forest_true_story_drink" to "Напиток \"Лесная быль\"",
        "petrovsky_drink" to "Напиток \"Петровский\"",
        "fanta_drink" to "Напиток \"Фанта\"",
        "orange_drink" to "Напиток апельсиновый",
        "orange_or_lemon_drink" to "Напиток апельсиновый или лимонный",
        "quince_drink_with_cream" to "Напиток из айвы со сливками",
        "quince_drink_with_sour_cream" to "Напиток из айвы со сметаной",
        "hawthorn_drink" to "Напиток из боярышника",
        "hawthorn_drink_with_oat_broth" to "Напиток из боярышника с овсяным отваром",
        "lingonberry_drink" to "Напиток из брусники",
        "jam_drink" to "Напиток из варенья",
        "cherry_drink_with_raisins" to "Напиток из вишни с изюмом",
        "dried_apricot_drink" to "Напиток из кураги",
        "syrup_drink" to "Напиток из сиропа",
        "pumpkin_drink" to "Напиток из тыквы",
        "cranberry_drink" to "Напиток клюквенный",
        "rowanushka_drink" to "Напиток Рябинушка",
        "apple_drink" to "Напиток яблочный",
        "apple_drink_with_honey" to "Напиток яблочный с медом",
        "barberry_infusion" to "Настой барбарисовый",
        "nogai_tea_karachay_cherkess_national_drink" to "Ногайский чай (карачаево-черкесский национальный напиток)",
        "rosehip_decoction" to "Отвар из шиповника",
        "pinemen_kuslyat_oat_kissel_mordovian_national_dish" to "Пинемень куслят (кисель овсяный - мордовское национальное блюдо)",
        "sbiten" to "Сбитень",
        "novonikolaevsky_sbiten" to "Сбитень по Новониколаевски",
        "student_drink" to "Студенческий напиток",
        "pumpkin_kissel" to "Тыквенный кисель",
        "bread_kvass_2" to "Хлебный квас",
        "lingonberry_tea" to "Чай брусничный",
        "oregano_tea" to "Чай из душицы",
        "rowan_tea" to "Чай рябиновый",
        "tea_with_lemon" to "Чай с лимоном",
        "tea_with_milk_or_cream" to "Чай с молоком или сливками",
        "tea_with_sugar_jam_honey" to "Чай с сахаром, вареньем, джемом, медом, повидлом",
        "tea_with_apples" to "Чай с яблоками",
        "fruit_tea_with_apricots" to "Чай фруктовый с абрикосами",
        "bilberry_with_milk" to "Черника с молоком",
        "apple_punch" to "Яблочный пунш",
        "berry_liqueur" to "Ягодная наливка",
        "apricot_souffle" to "Абрикосовое суфле",
        "orange_baskets_with_cream" to "Апельсиновые корзиночки с кремом",
        "orange_dessert" to "Апельсиновый десерт",
        "oranges_in_vanilla_sauce" to "Апельсины в ванильном соусе",
        "meringue" to "Безе",
        "meringue_2" to "Безе (2)",
        "egg_white_biscuit" to "Бисквит из яичных белков",
        "oat_flake_pancakes" to "Блинчики из овсяных хлопьев",
        "pancakes_with_poppy_seeds" to "Блинчики с маком",
        "pancakes_with_carrots" to "Блинчики с морковью",
        "pancakes_with_meat_liver_cottage_cheese_apple_filling_jam" to "Блинчики с мясным, ливерным, творожным, яблочным фаршем, джемом, повидлом или вареньем",
        "semi_finished_pancake_shell" to "Блинчики-полуфабрикат (оболочка)",
        "pancakes_2" to "Блины",
        "buckwheat_pancakes" to "Блины гречневые",
        "guriev_pancakes" to "Блины гурьевские",
        "dehkan_pancakes" to "Блины дехканские",
        "boiled_potato_pancakes" to "Блины из вареного картофеля",
        "cabbage_pancakes" to "Блины из капусты",
        "pumpkin_pancakes" to "Блины из тыквы",
        "red_pancakes" to "Блины красные",
        "corn_pancakes_chechen_ingush_national_dish" to "Блины кукурузные (чечено-ингушское национальное блюдо)",
        "pancakes_with_sauerkraut" to "Блины с квашенной капустой",
        "slavic_pancakes" to "Блины славянские",
        "pancakes_with_sweet_sauce_old_elets_style" to "Блины со сладким соусом по-староелецки",
        "quick_pancakes" to "Блины-скородумки",
        "fresh_lingonberries_with_sugar" to "Брусника свежая с сахаром",
        "vanilla_cream" to "Ванильный крем",
        "vanilla_sauce" to "Ванильный соус",
        "waffles" to "Вафли",
        "waffles_on_waffle_iron" to "Вафли на вафельнице",
        "whipped_lemon_sauce" to "Взбитый лимонный соус",
        "whipped_chocolate_sauce" to "Взбитый шоколадный соус",
        "whipped_apple_sauce" to "Взбитый яблочный соус",
        "cherry_mousse" to "Вишневый мусс",
        "apple_dumplings" to "Галушки яблочные",
        "pears_stuffed_with_cottage_cheese" to "Груши, начиненные творогом",
        "thick_chocolate_sauce" to "Густой шоколадный соус",
        "birds_milk_dessert" to "Десерт \"Птичье молоко\"",
        "rainbow_sour_cream_dessert" to "Десерт из сметаны \"Радуга\"",
        "milk_dessert_chuvash_national_dish" to "Десерт молочный (чувашское национальное блюдо)",
        "barberry_jelly" to "Желе из барбариса",
        "crowberry_jelly" to "Желе из водяники",
        "raisin_jelly" to "Желе из кишмиша",
        "lemon_orange_or_mandarin_jelly" to "Желе из лимонов, апельсинов, мандаринов (лимон)",
        "milk_jelly" to "Желе из молока",
        "fresh_fruit_or_berry_jelly" to "Желе из плодов или ягод свежих",
        "fruit_or_berry_syrup_jelly" to "Желе из сиропа плодового или ягодного",
        "cream_jelly" to "Желе из сливок",
        "fruit_or_berry_extract_jelly" to "Желе из экстракта плодового или ягодного, или из сока плодового или ягодного натурального (сок)",
        "lemon_jelly" to "Желе лимонное",
        "meat_or_fish_jelly" to "Желе мясное или рыбное",
        "jelly_with_fresh_and_canned_fruits" to "Желе с плодами свежими и консервированными",
        "raisins_prunes_or_dried_apricots_in_honey_jelly_bashkir_national_dish" to "Изюм или чернослив, или курага в медовом желе (башкирское национальное блюдо)",
        "strawberries_with_cottage_cheese" to "Клубника с творогом",
        "strawberry_snow" to "Клубничный \"снег\"",
        "strawberry_pudding" to "Клубничный пудинг",
        "cranberry_mousse" to "Клюквенный мусс",
        "cranberry_sauce" to "Клюквенный соус",
        "dietary_gingerbread" to "Коврижка \"Диетическая\"",
        "kozinaki" to "Козинаки",
        "coffee_cream" to "Кофейный крем",
        "vanilla_sour_cream_cream" to "Крем ванильный из сметаны",
        "vanilla_chocolate_coffee_cream" to "Крем ванильный, шоколадный, кофейный",
        "strawberry_cream" to "Крем из клубники",
        "cranberry_and_pumpkin_cream" to "Крем из клюквы и тыквы",
        "rhubarb_cream" to "Крем из ревеня",
        "rye_bread_cream" to "Крем из ржаного хлеба",
        "currant_cream" to "Крем из смородины",
        "bilberry_cream" to "Крем из черники",
        "cottage_cheese_cream" to "Крем твороженный",
        "berry_cream" to "Крем ягодный",
        "croquant_cream" to "Крем-крокант",
        "mocha_cream" to "Крем-мокко",
        "kulaga" to "Кулага",
        "lantutiki" to "Лантутики",
        "lemon_cake" to "Лимонное пирожное",
        "lemon_cream" to "Лимонный крем",
        "lemon_snowball" to "Лимонный снежок",
        "lemon_sauce_2" to "Лимонный соус",
        "lemon_sauce_3" to "Лимонный соус (2)",
        "lemon_sauce_4" to "Лимонный соус (3)",
        "lemon_cottage_cheese" to "Лимонный творог",
        "raspberries_or_strawberries_with_milk_sour_cream_or_cream" to "Малина или земляника с молоком, сметаной или сливками",
        "apricot_marmalade" to "Мармелад из абрикосов",
        "apricot_marmalade_with_skin" to "Мармелад из абрикосов в кожице",
        "lingonberry_and_apple_marmalade" to "Мармелад из брусники и яблок",
        "bilberry_marmalade" to "Мармелад из черники",
        "honey_hill" to "Медовая горка",
        "surprise_ice_cream" to "Мороженое \"Сюрприз\"",
        "canned_fruit_or_berry_ice_cream" to "Мороженое с плодами или ягодами консервированными",
        "instant_coffee_mousse" to "Мусс из растворимого кофе",
        "rhubarb_mousse" to "Мусс из ревеня",
        "rye_flour_mousse" to "Мусс из ржаной муки",
        "currant_mousse" to "Мусс из смородины",
        "pumpkin_mousse" to "Мусс из тыквы",
        "cranberry_mousse_2" to "Мусс клюквенный",
        "lemon_mousse" to "Мусс лимонный",
        "apple_mousse_on_semolina" to "Мусс яблочный (на крупе манной)",
        "oladyi" to "Оладьи",
        "oladyi_2" to "Оладьи (2)",
        "carrot_oladyi" to "Оладьи из моркови",
        "pumpkin_oladyi" to "Оладьи из тыквы",
        "oladyi_with_raisins" to "Оладьи с изюмом",
        "oladyi_with_apples" to "Оладьи с яблоками",
        "oladyi_with_apples_2" to "Оладьи с яблоками (2)",
        "omelette_with_apples" to "Омлет с яблоками",
        "omelette_with_apples_2" to "Омлет с яблоками (2)",
        "omelette_with_apples_3" to "Омлет с яблоками (3)",
        "nut_cream" to "Ореховый крем",
        "russian_style_cottage_cheese_nuts" to "Орешки творожные по-русски",
        "blackberry_pastila" to "Пастила из ежевики",
        "viburnum_pastila" to "Пастила из калины",
        "koketka_cake" to "Пирожное \"Кокетка\"",
        "floating_islands" to "Плавающие острова",
        "rhubarb_pudding" to "Пудинг из ревеня",
        "rice_and_rhubarb_pudding" to "Пудинг из риса и ревеня",
        "cheese_pudding" to "Пудинг из сыра",
        "baked_cottage_cheese_pudding" to "Пудинг из творога, запеченный",
        "sour_cream_pudding" to "Пудинг на сметане",
        "nut_pudding" to "Пудинг ореховый",
        "rice_semolina_millet_pudding" to "Пудинг рисовый, манный, пшенный",
        "pear_pudding" to "Пудинг с грушами",
        "creamy_pudding_with_nuts" to "Пудинг сливочный с орехами",
        "rusk_pudding" to "Пудинг сухарный",
        "rhubarb_with_sugar" to "Ревень с сахаром",
        "rhubarb_with_rusks_and_cream" to "Ревень с сухарями и сливками",
        "apricot_sambuc" to "Самбук абрикосовый",
        "apricot_sambuc_2" to "Самбук из абрикосов",
        "apple_or_plum_sambuc" to "Самбук яблочный или сливовый",
        "russian_style_condensed_milk" to "Сгущенка по-русски",
        "celery_for_dessert" to "Сельдерей на десерт",
        "sweet_milk_sauce" to "Сладкий молочный соус",
        "sweet_rice_and_cottage_cheese_dish" to "Сладкое блюдо из риса и творога",
        "whipped_cream_or_sour_cream" to "Сливки или сметана взбитые",
        "plum_sauce" to "Сливовый соус",
        "currant_with_honey_and_almonds" to "Смородина с медом и миндалем",
        "currant_snow" to "Смородиновый \"снег\"",
        "snezhki" to "Снежки",
        "apricot_sauce" to "Соус абрикосовый",
        "strawberry_raspberry_or_cherry_sauce" to "Соус земляничный или малиновый, или вишневый",
        "lingonberry_and_cheese_sauce" to "Соус из брусники и сыра",
        "raisin_and_almond_sauce" to "Соус из изюма и миндаля",
        "cocoa_sauce" to "Соус из какао",
        "gooseberry_sauce" to "Соус из крыжовника",
        "apple_and_lingonberry_sauce" to "Соус из яблок и брусники",
        "cranberry_sauce_2" to "Соус клюквенный",
        "sour_cream_sauce" to "Соус сметанный",
        "apple_sauce" to "Соус яблочный",
        "souffle" to "Суфле",
        "vanilla_chocolate_nut_souffle" to "Суфле ванильное, шоколадное, ореховое",
        "syrniki_with_carrots" to "Сырники с морковью",
        "orange_cottage_cheese" to "Творог апельсиновый",
        "cottage_cheese_sauce" to "Творожный соус",
        "cherry_in_honeycomb_cake" to "Торт \"Вишня в сотах\"",
        "katerina_cake" to "Торт \"Катерина\"",
        "honey_cake" to "Торт \"Медовый\"",
        "male_ideal_cake" to "Торт \"Мужской идеал\"",
        "negro_cake" to "Торт \"Негр\"",
        "almost_prague_cake" to "Торт \"Почти \"Прага\"",
        "prague_cake" to "Торт \"Прага\"",
        "snow_mountain_cake" to "Торт \"Снежная горка\"",
        "chocolate_mazurka_cake" to "Торт \"Шоколадная мазурка\"",
        "sponge_cake_with_nuts" to "Торт бисквитный с орехами",
        "zebra_cake" to "Торт Зебра»",
        "potato_and_cottage_cheese_cake" to "Торт из картофеля с творогом",
        "pumpkin_cake" to "Торт из тыквы",
        "potato_cake" to "Торт картофельный",
        "liver_cake" to "Торт печёночный",
        "prague_cake_2" to "Торт Прага»",
        "black_prince_cake" to "Торт Черный принц»",
        "pumpkin_with_nuts" to "Тыква с орехами",
        "pumpkin_with_rhubarb" to "Тыква с ревенем",
        "pumpkin_with_fruits" to "Тыква с фруктами",
        "izhevsk_style_pumpkin_baked_with_fruits_udmurt_national_dish" to "Тыква, запеченная с фруктами, по-ижевски (удмуртское национальное блюдо)",
        "pumpkin_cream" to "Тыквенный крем",
        "stuffed_apples" to "Фаршированные яблоки",
        "fruit_macedoine" to "Фруктовый маседуан",
        "cold_apricot_dish" to "Холодное из абрикосов",
        "prunes_with_whipped_cream_or_sour_cream" to "Чернослив со сливками или сметаной взбитыми",
        "chocolate_ice_cream" to "Шоколадное мороженое",
        "chocolate_cream" to "Шоколадный крем",
        "chocolate_pudding" to "Шоколадный пудинг",
        "chocolate_sauce" to "Шоколадный соус",
        "shulyo_melna_oat_pancakes_mari_national_dish" to "Шульо мелна (блины овсяные - марийское национальное блюдо)",
        "apples_in_grillage" to "Яблоки в грильяже",
        "apples_in_jelly" to "Яблоки в желе",
        "baked_apples" to "Яблоки печеные",
        "baked_apples_2" to "Яблоки печеные (2)",
        "baked_apples_with_lingonberries" to "Яблоки печеные с брусникой",
        "apples_with_whipped_cream" to "Яблоки со взбитыми сливками",
        "apples_stuffed_with_carrots" to "Яблоки, фаршированные морковью",
        "apple_cream_sauce" to "Яблочно-сливочный соус",
        "apple_cream_2" to "Яблочный крем",
        "berry_mousse" to "Ягодный мусс",
        "egg_mousse" to "Яичный мусс",
        "beans_in_sauce" to "Бобовые в соусе",
        "boiled_legumes" to "Бобовые отварные",
        "boiled_legumes_2" to "Бобовые отварные (2)",
        "garnish_of_vegetables_1" to "Гарнир из овощей 1",
        "garnish_of_vegetables_2" to "Гарнир из овощей 2",
        "garnish_of_vegetables_3" to "Гарнир из овощей 3",
        "garnish_of_vegetables_4" to "Гарнир из овощей 4",
        "garnish_of_vegetables_5" to "Гарнир из овощей 5",
        "garnish_of_vegetables_6" to "Гарнир из овощей 6",
        "garnish_of_vegetables_7" to "Гарнир из овощей 7",
        "garnish_of_vegetables_8" to "Гарнир из овощей 8",
        "garnish_of_vegetables_9" to "Гарнир из овощей 9",
        "garnish_for_herring_and_boiled_fish_1" to "Гарнир из овощей к сельди и отварной рыбе 1",
        "garnish_for_herring_and_boiled_fish_2" to "Гарнир из овощей к сельди и отварной рыбе 2",
        "garnish_for_herring_and_boiled_fish_3" to "Гарнир из овощей к сельди и отварной рыбе 3",
        "garnish_for_herring_and_boiled_fish_4" to "Гарнир из овощей к сельди и отварной рыбе 4",
        "complex_garnish_1" to "Гарнир сложный 1",
        "complex_garnish_10" to "Гарнир сложный 10",
        "complex_garnish_11" to "Гарнир сложный 11",
        "complex_garnish_12" to "Гарнир сложный 12",
        "complex_garnish_13" to "Гарнир сложный 13",
        "complex_garnish_15" to "Гарнир сложный 15",
        "complex_garnish_16" to "Гарнир сложный 16",
        "complex_garnish_17" to "Гарнир сложный 17",
        "complex_garnish_18" to "Гарнир сложный 18",
        "complex_garnish_19" to "Гарнир сложный 19",
        "complex_garnish_2" to "Гарнир сложный 2",
        "complex_garnish_3" to "Гарнир сложный 3",
        "complex_garnish_5" to "Гарнир сложный 5",
        "complex_garnish_6" to "Гарнир сложный 6",
        "complex_garnish_7" to "Гарнир сложный 7",
        "complex_garnish_8" to "Гарнир сложный 8",
        "garnishes_for_sweet_soups" to "Гарниры к сладким супам",
        "nevskaya_cabbage" to "Капуста \"Невская\"",
        "fried_cabbage" to "Капуста жареная",
        "potatoes_in_milk" to "Картофель в молоке",
        "potatoes_in_milk_2" to "Картофель в молоке (2)",
        "potatoes_in_milk_3" to "Картофель в молоке (3)",
        "potatoes_in_foil" to "Картофель в фольге",
        "deep_fried_potatoes" to "Картофель жаренный во фритюре",
        "fried_potatoes_from_boiled" to "Картофель жареный (из вареного)",
        "fried_potatoes_from_raw" to "Картофель жареный (из сырого)",
        "young_potatoes_in_sour_cream" to "Картофель молодой в сметане",
        "homestyle_potatoes" to "Картофель по домашнему",
        "potatoes_baked_in_sour_cream_sauce" to "Картофель, запеченный в сметанном соусе",
        "potatoes_baked_with_pork" to "Картофель, запеченный со свининой",
        "potatoes_stewed_with_mushrooms" to "Картофель, тушённый с грибами",
        "potatoes_stewed_with_mushrooms_in_sour_cream" to "Картофель, тушенный с грибами в сметане",
        "potato_casserole_2" to "Картофельная запеканка",
        "potato_casserole_zero" to "Картофельная запеканка (0)",
        "french_style_potato_casserole" to "Картофельная запеканка по-французски",
        "potato_mass" to "Картофельная масса",
        "mashed_potatoes" to "Картофельное пюре",
        "potato_croquettes_2" to "Картофельные крокеты",
        "oksanovsky_style_potatoes" to "Картошка по Оксановски",
        "dumplings" to "Клецки",
        "dumplings_in_lemon_sauce" to "Клецки в лимонном соусе",
        "cabbage_dumplings" to "Клецки из капусты",
        "homemade_noodles" to "Лапша домашняя",
        "sauteed_carrots_in_butter" to "Морковь, пассерованная в масле",
        "plov_2" to "Плов",
        "rice_stuffed_tomatoes" to "Помидоры с рисом",
        "fried_tomatoes_eggplants_and_other_vegetables" to "Помидоры, баклажаны и другие овощи жареные",
        "profiteroles" to "Профитроли",
        "zucchini_puree" to "Пюре из кабачков",
        "potato_and_cabbage_puree" to "Пюре из картофеля и капусты",
        "potato_and_pumpkin_puree" to "Пюре из картофеля и тыквы",
        "potato_and_spinach_puree" to "Пюре из картофеля и шпината",
        "carrot_puree" to "Пюре из моркови",
        "onion_puree" to "Пюре из репчатого лука",
        "mashed_potatoes_2" to "Пюре картофельное",
        "spicy_beetroot" to "Свекла пикантная",
        "rutabaga_souffle" to "Суфле из брюквы",
        "vegetable_salad_2" to "Салат овощной",
// ... и так далее. Из-за огромного количества я ограничился первыми 500-600 строками. Для полного перевода потребуется автоматическая генерация.
    )

    val reverseMap: Map<String, String> = map.entries.associate { (en, ru) ->
        ru.lowercase() to en
    }

    fun getEnglishName(russianName: String): String? {
        return map.entries.find { it.value.equals(russianName, ignoreCase = true) }?.key
    }

    fun getEnglishDisplayName(russianName: String): String? {
        return getEnglishName(russianName)?.replace("_", " ")
    }

    fun getEnglishOrTransliteratedName(russianName: String): String {
        return getEnglishDisplayName(russianName) ?: transliterate(russianName)
    }

    fun transliterate(value: String): String {
        return value.map { ch ->
            val lower = ch.lowercaseChar()
            val tr = translitMap[lower]
            when {
                tr != null && ch.isUpperCase() -> tr.replaceFirstChar { it.uppercase() }
                tr != null -> tr
                ch == '№' -> "No"
                else -> ch.toString()
            }
        }.joinToString("")
    }

    fun getLocalizedName(russianName: String, languageCode: String): String {
        return if (languageCode.equals("ru", ignoreCase = true)) {
            russianName
        } else {
            getEnglishOrTransliteratedName(russianName)
        }
    }
}


